# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 560209ddea1430e1e79325940207d7a090adb6fbb24da75e983a8b8a298ece645fc31d4238f2e0e39ba2eb7ba0937502cd4045aeaedb5fe6f01233a5850251d0

test:
  secret_key_base: cd9a4e52b0d125e47b3446a736f19e8bcd960ea17c23685b34d4d0bd9db1530c6eec19b0ead3adf920e9d9a754031a083c025f2b2393d16bcc7f027eff12c7d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
